### ISSUE TITLE
Running uploaded PDB files through the structural motif search

### ISSUE THREAD

**Issue by tslaird** [rcsb/strucmotif-search#17]
I am obtaining an error when trying to perform a structural motif search on an uploaded pdb file:

ERROR: 500 Internal Server Error. The server encountered an unexpected condition which prevented it from fulfilling the request.
QUERY [ bfa2fe6f-ce63-4a6c-aed0-74bc570c0f16 ]. Unexpected error occurred: No Content

Are you only able to search motifs from proteins already in the rcsb pdb database?

**Comment by sbittrich** [comment]
Official support for uploaded files is quite limited at the moment. You'll need to run queries directly through the API at https://search.rcsb.org/, it's not supported by the rcsb.org frontend yet.

A base query is [here](https://search.rcsb.org/query-editor.html?json=%7B%22query%22%3A%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22strucmotif%22%2C%22parameters%22%3A%7B%22value%22%3A%7B%22data%22%3A%22%5B...%5D%22%2C%22format%22%3A%22cif%22%2C%22residue_ids%22%3A%5B%7B%22label_asym_id%22%3A%22A%22%2C%22struct_oper_id%22%3A%221%22%2C%22label_seq_id%22%3A221%7D%2C%7B%22label_asym_id%22%3A%22A%22%2C%22struct_oper_id%22%3A%221%22%2C%22label_seq_id%22%3A439%7D%2C%7B%22label_asym_id%22%3A%22A%22%2C%22struct_oper_id%22%3A%221%22%2C%22label_seq_id%22%3A441%7D%5D%7D%2C%22rmsd_cutoff%22%3A2%2C%22atom_pairing_scheme%22%3A%22ALL%22%7D%7D%2C%22return_type%22%3A%22assembly%22%2C%22request_options%22%3A%7B%22results_verbosity%22%3A%22verbose%22%2C%22scoring_strategy%22%3A%22combined%22%2C%22sort%22%3A%5B%7B%22sort_by%22%3A%22score%22%2C%22direction%22%3A%22desc%22%7D%5D%7D%7D). You'll need to replace the `data` attribute with the Base64-encoded CIF content you want to use to define your query motif. E.g., to search based on https://alphafold.ebi.ac.uk/entry/Q8W3K0, go to https://base64.guru/converter/encode/url and convert the [corresponding CIF](https://alphafold.ebi.ac.uk/files/AF-Q8W3K0-F1-model_v2.cif) file to Base64. Finally, paste that string as `data` attribute.

I'm working on a better solution.

**Comment by sbittrich** [comment]
@tslaird This feature is finally available. You can upload your own file at https://www.rcsb.org/search/advanced/strucmotif (switch the input mode in the top-left corner to "File Upload"). You can then use the "Open in Mol*" button to select the residues that compose your motif and launch your search.

Help documentation is available at https://www.rcsb.org/docs/search-and-browse/advanced-search/structure-motif-search#uploading-your-own-local-file.
