### ISSUE TITLE
Can the search target be restricted to high resolution structures?

### ISSUE THREAD

**Issue by yakomaxa** [rcsb/strucmotif-search#19]
Dear developers of strucmotif-search,

I'm a bioinformatician working with PDB structures and have been playing with strucmotif-search for past couples of weeks.
It works nicely, but I would like to ask a question to get more control because I'm very new to Java. 

My question is about how to  limit the search target to high resolution structures.

When I compose a query using side-chain configuration of interest and run the program, I sometimes get the result containing many low resolution structures. I noticed that low resolution structures (most likely they are cryoEM models) returns weirdly low RMSDs compared to usual X-ray structures. As I'm interested to extract the side-chain similarity against high-resolution structures, I would like to limit the search targets to those with its resolution above certain threshold. Are there any means to achieve this with this softwares?

Thank you very much for making this software public. 
Best.

**Comment by sbittrich** [comment]
Hi @yakomaxa,

No, that's not possible with the library/code itself (pretty much all metadata is removed from the stored structure files and the resolution is unknown at runtime).

You can add upstream or downstream filtering operations to achieve the desired behavior. If you index your own data you can simply avoid adding anything that doesn't match your quality criteria. If you use this code via rcsb.org then you can add a resolution filter directly to your query. If you use this library programmatically you could query the rcsb.org Data API to retrieve the resolution value of each matched structure and filter based on that.
Let me know if you need help with any of that, the best solution depends on your use case.

Cheers,
Sebastian

**Comment by yakomaxa** [comment]
@JonStargaryen 

Thank you for quick reply and clarifying the limitations of the software. 

I appreciate your suggestion to use RCSB Data API. I'm using the library programmatically but not fluent in java, so I will compose post-processing script in other language to filter the result using the API. 

Regards,
Koya

**Comment by sbittrich** [comment]
Sounds good, feel free to reopen if you run into any issues.
